
all:
	-(cd asrc; make)
	-(cd bjt; make)
	-(cd bsim1; make)
	-(cd bsim2; make)
	-(cd cap; make)
	-(cd cccs; make)
	-(cd ccvs; make)
	-(cd csw; make)
	-(cd dio; make)
	-(cd ind; make)
	-(cd isrc; make)
	-(cd jfet; make)
	-(cd ltra; make)
	-(cd mes; make)
	-(cd mos1; make)
	-(cd mos2; make)
	-(cd mos3; make)
	-(cd mos6; make)
	-(cd res; make)
	-(cd sw; make)
	-(cd tra; make)
	-(cd urc; make)
	-(cd vccs; make)
	-(cd vcvs; make)
	-(cd vsrc; make)

clean:
	(cd asrc; make clean)
	(cd bjt; make clean)
	(cd bsim1; make clean)
	(cd bsim2; make clean)
	(cd cap; make clean)
	(cd cccs; make clean)
	(cd ccvs; make clean)
	(cd csw; make clean)
	(cd dio; make clean)
	(cd ind; make clean)
	(cd isrc; make clean)
	(cd jfet; make clean)
	(cd ltra; make clean)
	(cd mes; make clean)
	(cd mos1; make clean)
	(cd mos2; make clean)
	(cd mos3; make clean)
	(cd mos6; make clean)
	(cd res; make clean)
	(cd sw; make clean)
	(cd tra; make clean)
	(cd urc; make clean)
	(cd vccs; make clean)
	(cd vcvs; make clean)
	(cd vsrc; make clean)

install:
	(cd asrc; make install)
	(cd bjt; make install)
	(cd bsim1; make install)
	(cd bsim2; make install)
	(cd cap; make install)
	(cd cccs; make install)
	(cd ccvs; make install)
	(cd csw; make install)
	(cd dio; make install)
	(cd ind; make install)
	(cd isrc; make install)
	(cd jfet; make install)
	(cd ltra; make install)
	(cd mes; make install)
	(cd mos1; make install)
	(cd mos2; make install)
	(cd mos3; make install)
	(cd mos6; make install)
	(cd res; make install)
	(cd sw; make install)
	(cd tra; make install)
	(cd urc; make install)
	(cd vccs; make install)
	(cd vcvs; make install)
	(cd vsrc; make install)
